# Generated by Django 3.0.2 on 2020-02-04 02:28

from django.db import migrations, models
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user_lastname',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user_name',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=video_encoding.fields.VideoField(default=1, height_field='height', upload_to='', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
