# Generated by Django 3.0.2 on 2020-02-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20200203_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='En Proceso', max_length=50, null=True),
        ),
    ]
