# Generated by Django 3.0.2 on 2020-02-16 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='email',
            field=models.EmailField(default='c@c.c', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='image_path',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
    ]
