# Generated by Django 3.0.2 on 2020-02-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20200216_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='comment',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(default='En Proceso', max_length=50),
        ),
    ]
