# Generated by Django 3.0.2 on 2020-02-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
