# Generated by Django 3.0.2 on 2020-02-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_contest_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='contest_id',
            new_name='contest',
        ),
        migrations.AlterField(
            model_name='contest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
