# Generated by Django 2.1 on 2020-03-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('begin_at', models.DateTimeField(auto_now_add=True, verbose_name='date begin')),
                ('end_at', models.DateTimeField(verbose_name='date end')),
            ],
        ),
    ]
